### PR TITLE
Rollup build setup

### PR DESCRIPTION
**Pull request by greglobinski**

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
We should probably enforce the same rules as the mansion repo

**Comment by KyleAMathews** [comment]
I've been using https://github.com/developit/microbundle for this sort of thing which simplifies setup.

**Comment by greglobinski** [comment]
> We should probably enforce the same rules as the mansion repo for eslint, babel etc

@abhiaiyer91  I believe I did it with this PR https://github.com/gatsby-inc/gatsby-interface/pull/2#issuecomment-498045345

but do you mean  we should go with the exact setup? The ones on Cloud is for Typescript, so I removed the Typescript stuff from the setup, like for example I changed `parser` to `babel-eslint` in `.eslintrc`. I can revert the changes.

**Comment by greglobinski** [comment]
> I've been using [developit/microbundle](https://github.com/developit/microbundle) for this sort of thing which simplifies setup.

@KyleAMathews 	I will try it

**Pull request closed without merging**
