### PR TITLE
chore: add knob to control `variant` to the <Notification> "Tones" story 

### PR DESCRIPTION
**Pull request by fk**
Extracted from #271

### CODE REVIEW

**Comment by Elanhant** [comment]
Hm, my idea was that in 99% cases knobs would only be used in "Sandbox" stories; is there a specific reason for adding `variant` to `Tones`?

**Comment by fk** [comment]
Yes, to see all of them at a glance, instead of using the sandbox to click through one-by-one. We could adjust the sandbox, or even use s/th like https://github.com/evgenykochetkov/react-storybook-addon-props-combinations instead?!

**Comment by Elanhant** [comment]
@fk could you please check #279? I hope it can be a good alternative.

**Comment by fk** [comment]
#279 def. is nice! 🎉

Still wondering about visual regression tests :-P ;-) — but #279 def. does scratch my itch, closing this!

**Pull request closed without merging**
