### PR TITLE
Increase readability of RawLogs messages

### PR DESCRIPTION
**Pull request by greglobinski**
# Purpose 

Make the raw logs messages easier to read. https://app.clubhouse.io/gatsbyjs/story/17431/make-rawlogs-more-readable

The PR is a follow up to https://github.com/gatsby-inc/gatsby-interface/pull/413

Screenshot 2020-10-21 at 08 43 00

Screenshot 2020-10-21 at 08 42 43

### CODE REVIEW

**Review by fk — APPROVED** [review]

**Review by Elanhant — APPROVED** [review]
✨

**Comment by Elanhant** [comment]
Hm, CI is complaining:
> Error: Evaluation failed: TypeError: message.replaceAll is not a function

We probably need a polyfill similar to what we have for `interpolateMessage` in Cloud.

**Comment by greglobinski** [comment]
> Hm, CI is complaining:

I switched to `replace()` and we are good

**Review by Elanhant — APPROVED** [review]
:shipit:

**Pull request merged**
